### ISSUE TITLE
How to run in device or simulator?

### ISSUE THREAD

**Issue by zh-wowtv** [Urigo/Ionic2-MeteorCLI-WhatsApp#1]
Normally we can run ionic in device or simulator like this:

> ionic run ios

Or goto platform to open project file to run. But how to run in this application? Thanks.

**Comment by dotansimha** [comment]
We use Meteor CLI, so first you need to make sure that you have the platform on you project:

```
$ meteor add-platform ios
```

And then run it:

```
$ meteor run ios 
```
