### ISSUE TITLE
How to run as iOS?

### ISSUE THREAD

**Issue by ghost** [Urigo/Ionic2-MeteorCLI-WhatsApp#11]
meteor run

uses the Android theme by default when I load the app in the browser. How do I tell it to use the iOS theme without using Cordova and running meteor run ios?

**Comment by mmazloum** [comment]
You have to provide a ionic object as you boot your ionic app like this (in the app.module) : 
    IonicModule.forRoot(AppComponent, {
      mode: 'ios',
      iconMode: 'ios',
      backButtonText: '',
      backButtonIcon: 'ios-arrow-round-back',
      // pageTransition: 'md-transition',
      menuType: 'overlay',
      platforms: {
       md: {
        //  menuType: 'push',
        pageTransition: 'md-transition'
       }
      }
    }),

**Comment by dotansimha** [comment]
+1 @mmazloum.

@alstephan, please refer to Ionic 2 documentation: http://ionicframework.com/docs/v2/theming/platform-specific-styles/
