### ISSUE TITLE
Step 6: Users not showing up 'New Chat' modal

### ISSUE THREAD

**Issue by nigelpasco** [Urigo/Ionic2-MeteorCLI-WhatsApp#16]
Hi,

I have followed tutorial right through, however have noticed that the user list is not showing when the 'New Chat' modal is initiated.

I have checked the subscription and note that am subscribed to Users document. I have also tried copy the files direct from the github repository, to confirm that I was not missing something important, and have the same issue.

Among a few seeming non-related typescript errors, there is this error in the console:

```
server/imports/publications/chats.publication.ts (10, 8): Property 'publishComposite' does not exist on type 'typeof Meteor'.
server/imports/publications/chats.publication.ts (10, 46): Cannot find name 'PublishCompositeConfig'.
server/imports/publications/chats.publication.ts (19, 8): Cannot find name 'PublishCompositeConfig1'.
server/imports/publications/chats.publication.ts (27, 8): Cannot find name 'PublishCompositeConfig1'.

```

Other than that, I can nothing wrong with the code, as per the tutorial.

thank you.

**Comment by pkitatta** [comment]
Did you ever find a solution?

**Comment by michaelb-01** [comment]
I'm having the same issue, any solution?

**Comment by kapil5harma** [comment]
Any solutions yet?
