### ISSUE TITLE
Update tutorial for Ionic 2 RC / Angular 2 Final

### ISSUE THREAD

**Issue by themastersoda** [Urigo/Ionic2-MeteorCLI-WhatsApp#3]
First of all, huge thanks for these great tutorials. It really helps getting hang of things quicker by studying these amazing lessons.

Since Ionic 2 reached RC1 and it's API is pretty much close to final at the moment, do you plan on updating whatsapp tutorial from the Ionic CLI perspective? I have developed an app using ionic 2 beta with angular 2 RC4 for the mobile version which connects to remote meteor server that has it's own angular 2 client for the website part of it, but since then Ionic has had some serious changes along with angular 2 itself and an updated version of this tutorial for Ionic CLI would really help to make the upgrade process smoother.

Again, thanks a lot for your great work, it is really appreciated.

**Comment by msio** [comment]
+1

**Comment by Urigo** [comment]
for the CLI you should track this repo - https://github.com/DAB0mB/ionic2-meteor-messenger

Ionic's new CLI has some issues with Rollup, they are working on a version with Webpack and when it will be out we will update the Ionic CLI tutorial as well

**Comment by dotansimha** [comment]
Done!
