### ISSUE TITLE
Not having luck on following the tutorial

### ISSUE THREAD

**Issue by chhuang215** [Urigo/Ionic2-MeteorCLI-WhatsApp#7]
I followed the tutorial up to the end of chat page (step 2) and I realize I'm still getting a blank page. Seems like the tabs' opacity is set to 0 and wasn't able to declare itself to be ready. Not sure where I'm doing wrong, is there a global npm package I should already have in advance?

**Comment by dotansimha** [comment]
@chhuang215 we changed and fixed a lot of issues in the tutorial in the last days, can you please try again with the latest tutorial?
Please re-open if you still having issues.
