### ISSUE TITLE
SMS is not defined

### ISSUE THREAD

**Issue by tafelito** [Urigo/Ionic2-MeteorCLI-WhatsApp#9]
Hi @dotansimha , after step 5.16 when I try to run the app, its giving me this error

```
W20161104-12:58:26.212(-4)? (STDERR) ReferenceError: SMS is not defined
W20161104-12:58:26.212(-4)? (STDERR)     at meteorInstall.server.imports.api.sms.js (server/imports/api/sms.ts:7:3)
```

Even after adding the typings as it says right before step 5.3

`typings install dt~meteor-accounts-phone --save --global`

**Comment by dotansimha** [comment]
@tafelito can you try with the recent tutorial? and please re-open the issue if you're still having issues.
